### ISSUE TITLE
Błąd czy budowaniu projektu mavenem

### ISSUE THREAD

**Issue by EskaelDev** [LechMadeyski/JavaMetrics#3]
```
> mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< pl.edu.pwr.master:java-metrics >-------------------
[INFO] Building java-metrics 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ java-metrics ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ java-metrics ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ java-metrics ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 50 source files to D:\Repos\PBR20M6\JavaMetrics\target\classes
[INFO] /D:/Repos/PBR20M6/JavaMetrics/src/main/java/pl/edu/pwr/master/core/MetricGenerator.java: Some input files use unchecked or unsafe operations.
[INFO] /D:/Repos/PBR20M6/JavaMetrics/src/main/java/pl/edu/pwr/master/core/MetricGenerator.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ java-metrics ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ java-metrics ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to D:\Repos\PBR20M6\JavaMetrics\target\test-classes
[INFO] /D:/Repos/PBR20M6/JavaMetrics/src/test/java/pl/edu/pwr/master/core/ClassMetricStrategyTest.java: D:\Repos\PBR20M6\JavaMetrics\src\test\java\pl\edu\pwr\master\core\ClassMetricStrategyTest.java uses unchecked or unsafe operations.
[INFO] /D:/Repos/PBR20M6/JavaMetrics/src/test/java/pl/edu/pwr/master/core/ClassMetricStrategyTest.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ java-metrics ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running pl.edu.pwr.master.AppTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 s - in pl.edu.pwr.master.AppTest
[INFO] Running pl.edu.pwr.master.core.ClassMetricStrategyTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.618 s <<< FAILURE! - in pl.edu.pwr.master.core.ClassMetricStrategyTest
[ERROR] getClassAccessorMethods{CompilationUnit, String[]}[1]  Time elapsed: 0.009 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:
expected: <public int getSampleField() {
    return sampleField;
}> but was: <public int getSampleField() {
    return sampleField;
}>
        at pl.edu.pwr.master.core.ClassMetricStrategyTest.lambda$getClassAccessorMethods$0(ClassMetricStrategyTest.java:47)
        at pl.edu.pwr.master.core.ClassMetricStrategyTest.getClassAccessorMethods(ClassMetricStrategyTest.java:43)

[INFO] Running pl.edu.pwr.master.core.MethodMetricStrategyTest
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.004 s - in pl.edu.pwr.master.core.MethodMetricStrategyTest
[INFO] Running pl.edu.pwr.master.core.MetricStrategyTest
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.003 s - in pl.edu.pwr.master.core.MetricStrategyTest
[INFO] Running pl.edu.pwr.master.input.CsvReaderTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in pl.edu.pwr.master.input.CsvReaderTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ClassMetricStrategyTest.getClassAccessorMethods:43->lambda$getClassAccessorMethods$0:47 expected: <public int getSampleField() {
    return sampleField;
}> but was: <public int getSampleField() {
    return sampleField;
}>
[INFO]
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 4
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.346 s
[INFO] Finished at: 2020-05-06T15:28:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project java-metrics: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Repos\PBR20M6\JavaMetrics\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by arekziobrowski** [comment]
Powiązane z #1
